### ISSUE TITLE
FTP Response

### ISSUE THREAD

**Issue by Hauraky** [Nexific/dart_ftpclient#1]
Hi
I encountered an problem with ftp response… 
my ftp respond in this way:
Unknown response from FTP server (Response: 220-
I have modify your ftpsocket.dart in line 66  if (!sResponse.startsWith('220')) { removing the space. 
I removing the space in line 74 and 82 too.
In this way everything goes ok.

**Comment by virtualmarc** [comment]
Fixed in Release 0.4.0, please update the version and try again!
