### ISSUE TITLE
socket closing bug

### ISSUE THREAD

**Issue by salim-lachdhaf** [Nexific/dart_ftpclient#16]
**Describe the bug**
if we are disconnected (no internet) then the socket is NULL, however, we pass in ftpclient.disconnect() in finally witch call _socket.closeSync(); so the app crashes.

```
void connect(String user, String pass) {
    _log.log('Connecting...');
    _socket = RawSynchronousSocket.connectSync(host, port);  <- this crashes and the crash maintained by try catch as result we have  _socket =Null
...
}
```

```
void disconnect() {
    _log.log('Disconnecting...');

    try {
      sendCommand('QUIT');
    } catch (ignored) {
      // Ignore
    } finally {
      _socket.closeSync();// <- here it crashes
    }

    _log.log('Disconnected!');
  }
```

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'closeSync' was called on null.`

**Expected behavior**
maybe as solution we have to surrond ` _socket.closeSync()` with try catch or test if `_socket !=null`

**Platform:**
 - Flutter

**Smartphone (when using Flutter):**
 - Device: [Gallaxy Note]

**FTP Server Software**
- ProFTPd

**Comment by virtualmarc** [comment]
@salim-lachdhaf Please add a commend why you closed this bug!
