### ISSUE TITLE
can not download an empty file

### ISSUE THREAD

**Issue by salim-lachdhaf** [Nexific/dart_ftpclient#17]
**Describe the bug**
if you have an empty file on the FTP the download get freezed

**To Reproduce**
1. upload or create an empty txt file on the FTP
2. try with the plugin to download that file
3. download not working 

**Platform:**
 - Flutter

**Smartphone (when using Flutter):**
 - Device: Samsung Note

**FTP Server Software**
- ProFTPd

**Comment by virtualmarc** [comment]
@salim-lachdhaf Please add a commend why you closed this bug!
