### ISSUE TITLE
Directory List

### ISSUE THREAD

**Issue by Hauraky** [Nexific/dart_ftpclient#8]
Hello,
I tried to get the list of files in my FTP directory using the listDirectoryContent () function without success. 
Debugging the code, I saw that in the directory.dart file at line 99
sResponse = _socket.readResponse (); goes in times out. Then I added a print of sResponse to the previous line and I get this:
I/flutter (17207): 150 Accepted data connection
I/flutter (17207): 226-Options: -a -l 
I/flutter (17207): 226 4 matches total

So the server has already responded with 226.
I commented the line 99 and I changed line 100 on if (! SResponse.contains ('226')) {
just to go on...

After, at line 106 String.fromCharCodes (lstDirectoryListing) .split ('\ n'). ForEach ((line) {
I get others exceptions because the FTPEntry.dart class
does not contain the following properties:
FTPException: Unknown FTPEntry property 'sizd = 4096'
FTPException: Unknown FTPEntry property 'UNIX.uid = 1975'
FTPException: Unknown FTPEntry property 'UNIX.gid = 1974'

I remain available for clarifications or tests.

**Comment by virtualmarc** [comment]
Can you tell us what FTP Server software you use?
This could help us with testing against it. (We only tested the lib with ProFTPd)

**Comment by Hauraky** [comment]
Pure-FTPd
I attached verbose Filezilla log on the first connection to my FTP server.

[FilezillaLog.txt](https://github.com/Nexific/dart_ftpclient/files/4340502/FilezillaLog.txt)

**Comment by virtualmarc** [comment]
Thanks, I published a new Version (0.6.0) with some fixes.
Please try if it works better.

I'll set up a Pure-FTPd testsystem to check against it.

**Comment by Hauraky** [comment]
About listDirectoryContent() now works good.
Instead about FtpUpload Buffer Size not good notice.
Setting the new parameter buffersize, I found always difference between original file size and uploaded file size.
It works only setting small value for buffersize = 32 or added a sleep before disconnect function.
Let me know what tests I will can do for you.

**Comment by virtualmarc** [comment]
Ok, ao I can close this issue and will investigate the upload a bit further.

**Comment by gargakshit** [comment]
Currently, on 0.6.0, directory listing is not working
Server: proFTPd
Logs:
flutter: [18.03.2020 03:34:59.779] > TYPE A
flutter: [18.03.2020 03:34:59.881] < 200 Type set to A
flutter: [18.03.2020 03:34:59.882] > PASV
flutter: [18.03.2020 03:34:59.985] < 227 Entering Passive Mode (192,168,1,44,172,149).
flutter: [18.03.2020 03:34:59.986] > MLSD
flutter: [18.03.2020 03:35:00.099] < 150 Opening ASCII mode data connection for MLSD
flutter: [18.03.2020 03:35:01.204] <
flutter: FTPException: Can't get content of directory. (Response: )
